### ISSUE TITLE
Fix: dependabot config

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/cojac#19]
The dependabot config is invalid. Should be: 

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```
